name: finding_apartments_yangon
description: flatmate yangon.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0+3  
  page_transition: ^2.0.9
  animations: ^2.0.7
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  overlay_support: ^2.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.8.3
  cached_network_image: ^3.2.3
  flutter_image_slider: ^0.0.2
  photo_view: ^0.14.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.12
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.4
  multi_image_picker_view: ^0.0.17
  animated_introduction: ^1.0.4
  animated_icon: ^0.0.5
  http: ^1.1.0
  flutter_verification_code: ^1.1.7
  flutter_easyloading: ^3.0.5
  image_cropper: ^5.0.0
  internet_connection_checker_plus: ^2.0.0
  flutter_animate: ^4.2.0+1
  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/home_icon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/jsons/

 



  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Regular.ttf
  